namespace GhostSharp.Entities
{
    /// <summary>
    /// Choose which exceptions, if any, to suppress.
    /// The default is None (throw all exceptions).
    /// </summary>
    public enum SuppressionLevel
    {
        /// <summary>
        /// No exceptions are suppressed. They're all rethrown.
        /// </summary>
        None = 0,

        /// <summary>
        /// Exceptions generated by a Ghost response (Tag not found, User not found)
        /// are suppressed.
        /// </summary>
        GhostOnly = 1,

        /// <summary>
        /// All exceptions are suppressed.
        /// </summary>
        All = 2
    }
}
